export const members = [
  {
    id: 1,
    Subject: "منصة التفاوض الأردن ولبنان",
    name: "ليال باسيل",
    image: "/images/layale.jpg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
  },
  {
    id: 2,
    name: "عصمت العياش",
    image: "/images/ismat.jpg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
  {
    id: 3,
    name: "مارون عبود",
    image: "/images/flags/lb.svg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
  },
  {
    id: 4,
    name: "فليمون وهبي",
    image: "/images/avatarPlaceholder.png",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
  {
    id: 5,
    name: "عصمت العياش",
    image: "/images/ismat.jpg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
  {
    id: 6,
    name: "مارون عبود",
    image: "/images/flags/lb.svg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
  },
  {
    id: 7,
    name: "فليمون وهبي",
    image: "/images/avatarPlaceholder.png",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
  {
    id: 8,
    name: "عصمت العياش",
    image: "/images/ismat.jpg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
  {
    id: 9,
    name: "مارون عبود",
    image: "/images/flags/lb.svg",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
  },
  {
    id: 10,
    name: "فليمون وهبي",
    image: "/images/avatarPlaceholder.png",
    lastmsg: "المتفاوض الرئيسي للدولة المعنية من خلال",
    online: true,
  },
];
